### ISSUE TITLE
Fix Bug where switching back to a human causes major errors

### ISSUE THREAD

**Issue by CrashCringle12** [TheMatrixNetwork/Server#1]
When you become a vampire, you get the Vampire Skilltree; however when switching back to human console is spammed with errors until you select a new skill

**Comment by TejasDesale** [comment]
"spammed" is not very helpful. The least you could do is paste the error log smh

**Comment by CrashCringle12** [comment]
Patched and updated in commit:
https://github.com/S1mple133/Matrix/commit/45fcdf8d9733afd3894d8b143f5dd691196aab53

Also ensures that users can't switch properly switch classes while a vampire (as intended)
