### ISSUE TITLE
Quick Weapon Leveling With Bending

### ISSUE THREAD

**Issue by Zyntrex** [TheMatrixNetwork/Server#3]
I have tested and confirmed, that Bending can greatly level Swords and Axes in a matter of minutes, with Firebending, Waterbending and Earthbending it gives a lot of experience with said weapons' proficiency, as an example, my Axes level was 40, and reached 101 within 5 minutes or less.

**Comment by CrashCringle12** [comment]
So I made some edits to mcmmo.
Modified the experience gained divisor (similar to a multiplier) to 2.5 for each of these skills. 
So that means that the experience you gain for Swords, Unarmed, and Axes is divided by 2.5.

**Comment by TejasDesale** [comment]
ok this is not an issue since mcmmo lvls go up to 1500 40 to 100 is not something that should have been solved

**Comment by CrashCringle12** [comment]
Hmm that is a fair point actually, there's an option for the experience to be calculated exponentially, so maybe we can write a better equation for it. Who feels like doing some math

**Comment by CrashCringle12** [comment]
I reverted back to 1 tho also

**Comment by CrashCringle12** [comment]
https://github.com/TheMatrixNetwork/plugins/blob/master/mcMMO/experience.yml
