### ISSUE TITLE
Essentials Signs conflict with signshop

### ISSUE THREAD

**Issue by HappenLTD** [TheMatrixNetwork/Server#8]
[https://i.imgur.com/v7b58Xa.png](url)

No idea why it happens and no idea if it should be fixed.

I'm just reporting it.

**Comment by CrashCringle12** [comment]
Essentials comes with its own version of signs to be used with shops, and signshop is its own thing as well. They overlap because they share a lot of sign names like [Buy].  I believe signshop takes priority and it is the superior one to use.

The warning has been silenced.
